dataset:
    name: cifar10
    input_size: 32
    classes: 10

training:
    batch_size: 128
    max_epochs: 1000
    warmup_epochs: 5
    learning_rate: 0.4
    temperature: 0.5

optimization:
    optimizer: SGD
    scheduler: True
    warmup: True
    cosine: True

model:
    backbone: resnet18
    projection_dim: 512

transform:
    gaussian_blur: True
    normalize:
        mean: [0.4914, 0.4822, 0.4465]
        std: [0.2023, 0.1994, 0.2010]
    jitter_strength: 0.5