dataset:
    name: cifar100
    input_size: 32

training:
    batch_size: 512
    max_epochs: 1000
    warmup_epochs: 5
    learning_rate: 0.4
    temperature: 0.5

optimization:
    optimizer: SGD
    scheduler: True
    warmup: True
    cosine: True

model:
    backbone: resnet18
    projection_dim: 512

transform:
    gaussian_blur: False
    normalize:
        mean: [0.5070, 0.4865, 0.4409]
        std: [0.2009, 0.1984, 0.2023]
    jitter_strength: 0.5