dataset:
    name: stl10
    input_size: 96
    classes: 10

training:
    batch_size: 256
    max_epochs: 1000
    warmup_epochs: 5
    learning_rate: 0.6
    temperature: 0.5

optimization:
    optimizer: LARS
    scheduler: True
    warmup: True
    cosine: True

model:
    backbone: resnet18
    projection_dim: 512

transform:
    gaussian_blur: True
    normalize:
        mean: [0.4467, 0.4398, 0.4066]
        std: [0.2242, 0.2215, 0.2239]
    jitter_strength: 0.5