dataset:
    name: svhn
    input_size: 32
    classes: 10

training:
    batch_size: 512
    max_epochs: 500
    warmup_epochs: 5
    learning_rate: 0.4
    temperature: 0.5

optimization:
    optimizer: LARS
    scheduler: True
    warmup: True
    cosine: True

model:
    backbone: resnet18
    projection_dim: 512

transform:
    gaussian_blur: False
    normalize:
        mean: [0.4377, 0.4438, 0.4728]
        std: [0.1980, 0.2010, 0.1970]
    jitter_strength: 0.5