dataset:
    name: cifar10
    input_size: 32
    global_crop_size: 28
    local_crop_size: 16
    classes: 10

training:
    batch_size: 128
    max_epochs: 100
    warmup_epochs: 10
    learning_rate: 0.0002
    teacher_temperature: 0.2
    student_temperature: 0.15

optimization:
    optimizer: AdamW
    warmup: True
    cosine: True

model:
    student_backbone: vitti
    student_projection_dim: 512
    teacher_backbone: vitti
    teacher_projection_dim: 512

transform:
    gaussian_blur: True
    normalize:
        mean: [0.4914, 0.4822, 0.4465]
        std: [0.2023, 0.1994, 0.2010]
    jitter_strength: 0.5
    crop_number: 4