dataset:
  classes: 10
  input_size: 32
  name: svhn
model:
  backbone: resnet18
  projection_dim: 512
optimization:
  cosine: true
  optimizer: LARS
  scheduler: true
  warmup: true
training:
  batch_size: 512
  learning_rate: 0.4
  max_epochs: 500
  temperature: 0.5
  warmup_epochs: 5
transform:
  gaussian_blur: false
  jitter_strength: 0.5
  normalize:
    mean:
    - 0.4377
    - 0.4438
    - 0.4728
    std:
    - 0.198
    - 0.201
    - 0.197
